# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.9.{build}

pull_requests:
  do_not_increment_build_number: true

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: GenericStl.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  parallel: true

  # MSBuild verbosity level
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**\*.Tests.dll'

#---------------------------------#
#       deploy configuration      #
#---------------------------------#

deploy:
- provider: NuGet
  api_key:
    secure: VahebLfISY1oJVsf6bwhwRYsOXp+4s3LqBYUmP63RDvf/MY1/3NhktTeG1UrR2Dx
  on:
    branch: master

#---------------------------------#
#       cache configuration       #
#---------------------------------#
cache:
  - packages                     # preserve "packages" directory in the root of build folder
